services:
  - type: web
    name: sasta-pdf
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: RENDER
        value: "true"
    healthCheckPath: /
